# Example compose file

version: '3'
services:
  helios:
    container_name: helios
    image: ghcr.io/m1nxy/helios:latest
    build: .
    command: npm run prod
    restart: unless-stopped
    # optional
    ports:
      - 6080:80
    env_file:
      - stack.env
    healthcheck:
      test: ["CMD", "npm", "run", "healthcheck"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "*/30 * * * * *" --cleanup
    restart: unless-stopped
